#!/usr/bin/env bash
#
# Migrate data from the Replit Postgres (source) to Neon (target).
#
# Prerequisites:
#   1. The target Neon database already has the schema applied
#      (run `npm run db:push` against the Neon DATABASE_URL first).
#   2. `pg_dump` and `psql` are available (Postgres 16+ recommended,
#      to match Neon's server version).
#
# Usage:
#   SOURCE_DATABASE_URL='postgresql://user:pass@replit-host/db'        \
#   TARGET_DATABASE_URL='postgresql://user:pass@neon-host/db?sslmode=require' \
#     ./scripts/migrate-db.sh
#
# Behavior:
#   - Dumps data only (no schema) from the source, in FK dependency order.
#   - Truncates target tables AND restores data in a single transaction
#     against the target. If anything fails, the entire restore is rolled
#     back and the target is left exactly as it was before the run.
#   - Uses the default COPY format, so ULIDs, timestamps, password hashes,
#     and foreign keys transfer byte-for-byte.
#   - Does NOT use --disable-triggers (which requires superuser on managed
#     Postgres like Neon); FK integrity is preserved instead by loading
#     parent tables before child tables.

set -euo pipefail

: "${SOURCE_DATABASE_URL:?SOURCE_DATABASE_URL is required (Replit Postgres URL)}"
: "${TARGET_DATABASE_URL:?TARGET_DATABASE_URL is required (Neon URL)}"

# Tables in FK dependency order: parents first (users, settings parents),
# then children (posts, accounts, sessions reference users).
TABLES=(
  users
  general_settings
  appearance_settings
  notifications_settings
  help_center_settings
  security_settings
  posts
  accounts
  sessions
  verification_tokens
)

DUMP_FILE="$(mktemp -t replit-pg-dump.XXXXXX.sql)"
COMBINED_FILE="$(mktemp -t replit-pg-restore.XXXXXX.sql)"
trap 'rm -f "$DUMP_FILE" "$COMBINED_FILE"' EXIT

echo "==> Dumping data from source..."
PG_DUMP_TABLE_ARGS=()
for t in "${TABLES[@]}"; do
  PG_DUMP_TABLE_ARGS+=( -t "public.$t" )
done

pg_dump \
  --data-only \
  --no-owner \
  --no-privileges \
  "${PG_DUMP_TABLE_ARGS[@]}" \
  "$SOURCE_DATABASE_URL" > "$DUMP_FILE"

echo "    dump size: $(wc -c < "$DUMP_FILE") bytes"

echo "==> Building combined truncate + restore script..."
TRUNCATE_LIST=$(IFS=, ; echo "${TABLES[*]}")
{
  echo "-- Auto-generated by scripts/migrate-db.sh"
  echo "TRUNCATE TABLE ${TRUNCATE_LIST//,/, } RESTART IDENTITY CASCADE;"
  cat "$DUMP_FILE"
} > "$COMBINED_FILE"

echo "==> Restoring into target (single transaction)..."
# --single-transaction wraps the whole file in BEGIN/COMMIT, so the
# TRUNCATE and the COPY blocks succeed or fail together.
psql "$TARGET_DATABASE_URL" \
  -v ON_ERROR_STOP=1 \
  --single-transaction \
  -f "$COMBINED_FILE"

echo "==> Verifying row counts..."
mismatch=0
for t in "${TABLES[@]}"; do
  src=$(psql "$SOURCE_DATABASE_URL" -At -v ON_ERROR_STOP=1 -c "SELECT COUNT(*) FROM public.$t;")
  tgt=$(psql "$TARGET_DATABASE_URL" -At -v ON_ERROR_STOP=1 -c "SELECT COUNT(*) FROM public.$t;")
  if [ "$src" = "$tgt" ]; then
    flag=""
  else
    flag="  MISMATCH"
    mismatch=1
  fi
  printf "    %-25s source=%s target=%s%s\n" "$t" "$src" "$tgt" "$flag"
done

if [ "$mismatch" -ne 0 ]; then
  echo "==> WARNING: row-count mismatch detected. Investigate before cutover."
  exit 2
fi

echo "==> Done."
